version: "3.3"
services:
  speer:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./:/speer
      - /speer/node_modules
    environment:
      HOST: "0.0.0.0"
