# ENV NODE_VERSION 18.19.0
FROM node:18

ARG SPEER_BACKEND_URL
ENV SPEER_BACKEND_URL=$SPEER_BACKEND_URL

WORKDIR /speer
COPY package.json ./

#enable pnpm
RUN corepack enable
RUN pnpm i

COPY . .
RUN pnpm run generate

CMD [ "pnpm", "run", "start" ]
