version: "3.3"
services:
  speer:
    build:
      context: .
      dockerfile: dockerfile.prod
    volumes:
      - ./src:/speer/src
      - ./files:/speer/files
      - ./emails:/speer/emails
      - ./.env:/speer/.env
      - ./.gitignore:/speer/.gitignore
      - ./changelog.json:/speer/changelog.json
    ports:
      - "9001:9001"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    command: --quiet --logpath /dev/null
    volumes:
      - /data/speer/db:/data/db

  redis:
    image: redis
    logging:
      driver: none
