version: "3.3"
services:
  speer:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./:/speer/
      - /speer/target
    ports:
      - 9001:9001
    depends_on:
      - mongo
      - redis
    environment:
      SPEER_SERVER_ADDRESS: 0.0.0.0:9001
      SPEER_REDIS_ADDRESS: redis:6379
      SPEER_MONGO_URL: mongodb://mongo:27017

  mongo:
    image: mongo
    command: --quiet --logpath /dev/null
    volumes:
      - /data/speer/db:/data/db

  redis:
    image: redis
    logging:
      driver: none
