// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Feedback { description: string, stepsToReproduce: Array<string>, type: string, version: string, date: Date, }