// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PusherMessage } from "./PusherMessage";
import type { SignalMessage } from "./SignalMessage";

export type Message = SignalMessage | PusherMessage;