// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MinimalDevice } from "./MinimalDevice";

export interface MeUser { _id: string, email: string, username: string, avatar: string, requests: Array<string>, friends: Array<string>, devices: Array<MinimalDevice>, confirmed: boolean, deleted: boolean, }