// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SignalMessage { peerData: string, remoteId: string, type: string, data: string | null, }